#!/bin/bash
# This is a simple build script, place your post-deploy but pre-start commands in this script.  This script gets executed directly, so it could 
# be python, php, ruby, etc.
#
# Use repository htaccess 
echo "Creating htaccess file"
cp -f ${OPENSHIFT_REPO_DIR}.openshift/config/.htaccess ${OPENSHIFT_REPO_DIR}/php/.htaccess
# To keep data after a new push
echo "Creating persistent anchor content directory"
if [ ! -d "$OPENSHIFT_DATA_DIR/content" ]; then
	mkdir -p $OPENSHIFT_DATA_DIR/content
	rm -rdf $OPENSHIFT_REPO_DIR/php/content
fi
echo "Creating persistent anchor config directory"
if [ ! -d "$OPENSHIFT_DATA_DIR/anchor/config" ]; then
	mkdir -p $OPENSHIFT_DATA_DIR/anchor/config
	rm-rdf $OPENSHIFT_REPO_DIR/php/anchor/config
fi
echo "Creating persistent anchor theme directory"
if [ ! -d "$OPENSHIFT_DATA_DIR/anchor/config" ]; then
	mkdir -p $OPENSHIFT_DATA_DIR/themes
	rm =rdf $OPENSHIFT_REPO_DIR/php/themes
fi
echo "Symlinking the directories..."
ln -sf $OPENSHIFT_DATA_DIR/content $OPENSHIFT_REPO_DIR/php/content
ln -sf $OPENSHIFT_DATA_DIR/anchor/config $OPENSHIFT_REPO_DIR/php/anchor/config
ln -sf $OPENSHIFT_DATA_DIR/anchor/themes $OPENSHIFT_REPO_DIR/php/themes
echo "Linking complete..."
